apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - name: mysql
      port: 3306
    - name: healthz
      port: 80
  selector:
    app: mysql
  type: NodePort

---

apiVersion: v1
data:
  mysql-root-password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: mysql-creds
type: Opaque

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: Always
        ports:
          - name: mysql
            containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-creds
                key: mysql-root-password
          - name: MYSQL_DATABASE
            value: mydb
