apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
  namespace: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - image: vault
        imagePullPolicy: Always
        name: vault
        ports:
        - containerPort: 8200
          name: vaultport
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  ports:
    - name: vault
      port: 8200
  selector:
    app: vault
