apiVersion: "enterprises.upmc.com/v1"
kind: "Customsecrets"
metadata:
  name: "static"
spec:
  secret: "static-secret"
  policy: "secret/foo"

--

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-app-static
  labels:
    app: sample-app-static
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app-static
    spec:
      containers:
      - name: sample-app-static
        image: nginx
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "50Mi"
            cpu: ".1"
        volumeMounts:
          - name: custom-secrets
            mountPath: /secrets
      volumes:
        - name: custom-secrets
          secret:
            secretName: static-secret